import Vue from 'vue'

import { Button, Menu, MenuItem, Submenu, MenuItemGroup, Card, Form, FormItem, Input, Select, Option, DatePicker, Carousel, CarouselItem, Rate, InputNumber, Tabs, TabPane, Table, TableColumn, Checkbox, Collapse, CollapseItem } from 'element-ui'

Vue.use(Button)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(Card)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Select)
Vue.use(Option)
Vue.use(DatePicker)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Rate)
Vue.use(InputNumber)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Checkbox)
// Vue.use(Message)
